/*
 * AllBinary Open License Version 1
 * Copyright (c) 2011 AllBinary
 * 
 * By agreeing to this license you and any business entity you represent are
 * legally bound to the AllBinary Open License Version 1 legal agreement.
 * 
 * You may obtain the AllBinary Open License Version 1 legal agreement from
 * AllBinary or the root directory of AllBinary's AllBinary Platform repository.
 * 
 * Created By: Travis Berthelot
 * 
 */
package org.allbinary.image.gui;

import org.allbinary.logic.communication.log.LogUtil;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import org.allbinary.graphics.displayable.CanvasStrings;
import org.allbinary.logic.communication.log.LogFactory;
import org.allbinary.string.CommonStrings;

public class ImageJPanel extends javax.swing.JPanel {
    protected final LogUtil logUtil = LogUtil.getInstance();


    private final CommonStrings commonStrings = CommonStrings.getInstance();
    private final CanvasStrings canvasStrings = CanvasStrings.getInstance();
    
    private boolean isDrawn = false;
    private BufferedImage bufferedImage;

    public ImageJPanel(BufferedImage bufferedImage) {
        initComponents();

        this.bufferedImage = bufferedImage;
        this.setSize(this.bufferedImage.getWidth(null),
                this.bufferedImage.getHeight(null));
    }

    public void paint(Graphics graphics) {
        if (!isDrawn) {
            logUtil.put(commonStrings.START, this, canvasStrings.PAINT);

            graphics.drawImage(bufferedImage, 0, 0,
                    this.bufferedImage.getWidth(null),
                    this.bufferedImage.getHeight(null), null);
            isDrawn = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
