<%
/*
 *Copyright (c) 2002 All Binary
 *All Rights Reserved.
 *Don't Duplicate or Distributed.
 *Trade Secret Information
 *For Internal Use Only
 *Confidential
 *Unpublished
 *
 *Created By: Travis Berthelot
 *Date: 11/29/02
 *
 *
 *Modified By         When       ?
 *
 */
%>
<%

   //windows in hedges
   final String CATEGORYDROPDOWNMENUCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CATEGORYDIR + "categoryDropDownMenu";
   final String CATEGORYLISTCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CATEGORYDIR + "categoryList";

   final String AUTHENTICATIONCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "authentication";
   final String CUSTOMERLINKSSTYLEONECOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "customerLinksStyleOne";
   final String CUSTOMERLINKSSTYLETWOCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "customerLinksStyleTwo";
   final String CUSTOMERLINKSSTYLETHREECOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "customerLinksStyleThree";
   final String MICROREGISTRATIONCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "microRegistration";
   final String MINIBASKETCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "miniBasket";
   final String MINIREGISTRATIONCOMPONENTTEMPLATEFILE = TEMPLATEDIR + CUSTOMERDIR + "miniRegistration";
   
   final String HELPCOMPONENTTEMPLATEFILE = TEMPLATEDIR + HELPDIR + "helpList";
   final String LIVEHELPCOMPONENTTEMPLATEFILE = TEMPLATEDIR + HELPDIR + "live/liveHelp";
   
   final String NEWSCOMPONENTTEMPLATEFILE = TEMPLATEDIR + NEWSDIR + "newsList";
   
   final String PARTNERSCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PARTNERSDIR + "partnersList";   
   
   final String CLEARANCEBESTCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "clearanceBest";   
   final String PRODUCTSEARCHCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "productSearch";
   final String HORIZONTALPRODUCTSEARCHCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "horizontalProductSearch";
   final String PRODUCTBESTCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "productsBest";
   final String PRODUCTNEWCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "productsNew";
   final String PRODUCTSPOPULARCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "productsPopular";
   final String SALEPRODUCTSCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "saleProducts";
   final String SPECIALSCOMPONENTTEMPLATEFILE = TEMPLATEDIR + PRODUCTSDIR + "specials";
   
   final String REBATEBESTCOMPONENTTEMPLATEFILE = TEMPLATEDIR + REBATESDIR + "rebatesBest";
   

   //Insert widgets
   viewNameKeyAndTemplateValueHashMap.put(CATEGORYDROPDOWNMENUCOMPONENT, CATEGORYDROPDOWNMENUCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(CATEGORYLISTCOMPONENT, CATEGORYLISTCOMPONENTTEMPLATEFILE);   
   
   viewNameKeyAndTemplateValueHashMap.put(AUTHENTICATIONCOMPONENT, AUTHENTICATIONCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(CUSTOMERLINKSSTYLEONECOMPONENT, CUSTOMERLINKSSTYLEONECOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(CUSTOMERLINKSSTYLETWOCOMPONENT, CUSTOMERLINKSSTYLETWOCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(CUSTOMERLINKSSTYLETHREECOMPONENT, CUSTOMERLINKSSTYLETHREECOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(MICROREGISTRATIONCOMPONENT, MICROREGISTRATIONCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(MINIBASKETCOMPONENT, MINIBASKETCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(MINIREGISTRATIONCOMPONENT, MINIREGISTRATIONCOMPONENTTEMPLATEFILE);
   
   viewNameKeyAndTemplateValueHashMap.put(HELPCOMPONENT, HELPCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(LIVEHELPCOMPONENT, LIVEHELPCOMPONENTTEMPLATEFILE);   
   
   viewNameKeyAndTemplateValueHashMap.put(NEWSCOMPONENT, NEWSCOMPONENTTEMPLATEFILE);
   
   viewNameKeyAndTemplateValueHashMap.put(PARTNERSCOMPONENT, PARTNERSCOMPONENTTEMPLATEFILE);
   
   viewNameKeyAndTemplateValueHashMap.put(CLEARANCEBESTCOMPONENT, CLEARANCEBESTCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(PRODUCTSEARCHCOMPONENT, PRODUCTSEARCHCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(HORIZONTALPRODUCTSEARCHCOMPONENT, HORIZONTALPRODUCTSEARCHCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(PRODUCTBESTCOMPONENT, PRODUCTBESTCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(PRODUCTNEWCOMPONENT, PRODUCTNEWCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(PRODUCTSPOPULARCOMPONENT, PRODUCTSPOPULARCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(SALEPRODUCTSCOMPONENT, SALEPRODUCTSCOMPONENTTEMPLATEFILE);
   viewNameKeyAndTemplateValueHashMap.put(SPECIALSCOMPONENT, SPECIALSCOMPONENTTEMPLATEFILE);
   
   viewNameKeyAndTemplateValueHashMap.put(REBATEBESTCOMPONENT, REBATEBESTCOMPONENTTEMPLATEFILE);

%>
