<%
/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
%>

<%
   /*
   //windows in hedges
   final String CATEGORYLISTCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "categoryList.xsl";
   final String CATEGORYLISTANDLINKCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "categoryListAndLink.xsl";   
   final String CATEGORIESLINKCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "categoryLink.xsl";   
   final String CATEGORIESDROPDOWNCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "categoryDropDownMenu.xsl";   
   
   final String CUSTOMERLINKSSTYLEONECOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "customerLinksStyleOne.xsl";
   final String CUSTOMERLINKSSTYLETWOCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "customerLinksStyleTwo.xsl";
   final String MINIBASKETCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "miniBasket.xsl";   
   
   final String REGISTERANDAUTHENTICATIONCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "registerAndAuthentication.xsl";
   
   final String HELPCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "helpList.xsl";   
   
   final String NEWSCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "newsList.xsl";   
   
   final String PARTNERSCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "partnersList.xsl";   
   
   final String CLEARANCEBESTCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "clearanceBest.xsl";
   final String CLEARANCELINKCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "clearanceLink.xsl";
   final String PRODUCTBESTCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "productBest.xsl";
   final String PRODUCTNEWCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "productsNew.xsl";
   final String PRODUCTSPOPULARCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "productsPopular.xsl";
   final String SALEPRODUCTSCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "saleProducts.xsl";
   final String SPECIALSCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "specials.xsl";
   final String PRODUCTSEARCHCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + PRODUCTSDIR + "productSearch.xsl";

   final String REBATELINKCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "rebateLink.xsl";
   final String REBATEBESTCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "rebatesBest.xsl";
   
   final String HOMELINKCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "homeLink.xsl";
   
   final String MISCCOMPONENTCUSTOMIZERTEMPLATEFILE = TEMPLATECUSTOMIZERDIR + CATEGORYDIR + "misc.xsl";

   //Insert widgets
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CATEGORYLISTCOMPONENT, CATEGORYLISTCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CATEGORYLISTANDLINKCOMPONENT, CATEGORYLISTANDLINKCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CATEGORIESLINKCOMPONENT, CATEGORIESLINKCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CATEGORIESDROPDOWNCOMPONENT, CUSTOMIZERDROPDOWNTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CUSTOMERLINKSTYLEONECOMPONENT, CUSTOMERLINKSTYLEONECOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CUSTOMERLINKSTYLETWOCOMPONENT, CUSTOMERLINKSTYLETWOCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CUSTOMERMINIBASKETCOMPONENT, CUSTOMERMINIBASKETCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(REGISTERANDAUTHENTICATIONCOMPONENT, REGISTERANDAUTHENTICATIONCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(HELPCOMPONENT, HELPCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PARTNERSCOMPONENT, PARTNERSCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CLEARANCEBESTCOMPONENT, CLEARANCEBESTCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(CLEARANCELINKCOMPONENT, CLEARANCELINKCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PRODUCTBESTCOMPONENT, PRODUCTBESTCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PRODUCTNEWCOMPONENT, PRODUCTNEWCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PRODUCTSPOPULARCOMPONENT, PRODUCTSPOPULARCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(SALEPRODUCTSCOMPONENT, SALEPRODUCTSCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(SPECIALSCOMPONENT, SPECIALSCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PRODUCTSEARCHCOMPONENT, PRODUCTSEARCHCOMPONENTCUSTOMIZERTEMPLATEFILE);

   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(PRODUCTSEARCHCOMPONENT, PRODUCTSEARCHCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(REBATELINKCOMPONENT, REBATELINKCOMPONENTCUSTOMIZERTEMPLATEFILE);
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(REBATEBESTCOMPONENT, REBATEBESTCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(HOMELINKCOMPONENT, HOMELINKCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   viewNameKeyAndTemplateCustomizerComponentsHashMap.put(MISCCOMPONENT, MISCCOMPONENTCUSTOMIZERTEMPLATEFILE);
   
   //Class Paths

   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CATEGORYLISTCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CATEGORYLISTANDLINKCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CATEGORIESLINKCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CATEGORIESDROPDOWNCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CUSTOMERLINKSTYLEONECOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CUSTOMERLINKSTYLETWOCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CUSTOMERMINIBASKETCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(REGISTERANDAUTHENTICATIONCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(HELPCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PARTNERSCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CLEARANCEBESTCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(CLEARANCELINKCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PRODUCTBESTCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PRODUCTNEWCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PRODUCTSPOPULARCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(SALEPRODUCTSCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(SPECIALSCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PRODUCTSEARCHCOMPONENT, BODYCLASSPATH);

   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(PRODUCTSEARCHCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(REBATELINKCOMPONENT, BODYCLASSPATH);
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(REBATEBESTCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(HOMELINKCOMPONENT, BODYCLASSPATH);
   
   viewNameKeyAndTemplateCustomizationClassPathsValueHashMap.put(MISCCOMPONENT, BODYCLASSPATH);
 */
%>
