/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package org.allbinary.input.automation.module.generic.configuration.profile.actions;


import org.allbinary.input.automation.module.DefaultListModelHelper;
import org.allbinary.logic.communication.log.LogUtil;
import org.allbinary.string.CommonStrings;

/**
 *
 * @author  USER
 */
public class GenericProfileActionsJPanel extends javax.swing.JPanel
{
    protected final LogUtil logUtil = LogUtil.getInstance();

    private final CommonStrings commonStrings = CommonStrings.getInstance();
    
    private GenericProfileActions genericProfileActions;
    
    private GenericProfileActionJPanel genericProfileActionJPanel;
    
    /** Creates new form genericProfileActionsJPanel */
    public GenericProfileActionsJPanel() 
        throws Exception
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        newProfileActionJDialog = new javax.swing.JDialog();
        newProfileActionJLabel = new javax.swing.JLabel();
        okNewProfileActionJButton = new javax.swing.JButton();
        newProfileActionJTextField = new javax.swing.JTextField();
        genericProfileActionsJPanel = new javax.swing.JPanel();
        genericProfileActionsJScrollPane = new javax.swing.JScrollPane();
        genericProfileActionsJList = new javax.swing.JList();
        newActionJButton = new javax.swing.JButton();
        deleteActionJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        blankGenericProfileActionJPanel = new javax.swing.JPanel();

        newProfileActionJDialog.setMinimumSize(new java.awt.Dimension(250, 150));
        newProfileActionJDialog.setResizable(false);
        newProfileActionJLabel.setText("New Action Name");

        okNewProfileActionJButton.setText("Ok");
        okNewProfileActionJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okNewProfileActionJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newProfileActionJDialogLayout = new javax.swing.GroupLayout(newProfileActionJDialog.getContentPane());
        newProfileActionJDialog.getContentPane().setLayout(newProfileActionJDialogLayout);
        newProfileActionJDialogLayout.setHorizontalGroup(
            newProfileActionJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProfileActionJDialogLayout.createSequentialGroup()
                .addGroup(newProfileActionJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newProfileActionJDialogLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(okNewProfileActionJButton))
                    .addGroup(newProfileActionJDialogLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(newProfileActionJLabel))
                    .addGroup(newProfileActionJDialogLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(newProfileActionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        newProfileActionJDialogLayout.setVerticalGroup(
            newProfileActionJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProfileActionJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProfileActionJLabel)
                .addGap(21, 21, 21)
                .addComponent(newProfileActionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(okNewProfileActionJButton)
                .addContainerGap())
        );

        genericProfileActionsJPanel.setPreferredSize(new java.awt.Dimension(10000, 10000));
        genericProfileActionsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                genericProfileActionsJListValueChanged(evt);
            }
        });

        genericProfileActionsJScrollPane.setViewportView(genericProfileActionsJList);

        newActionJButton.setText("New");
        newActionJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newActionJButtonActionPerformed(evt);
            }
        });

        deleteActionJButton.setText("Delete");
        deleteActionJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteActionJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveJButtonActionPerformed(evt);
            }
        });

        blankGenericProfileActionJPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        javax.swing.GroupLayout blankGenericProfileActionJPanelLayout = new javax.swing.GroupLayout(blankGenericProfileActionJPanel);
        blankGenericProfileActionJPanel.setLayout(blankGenericProfileActionJPanelLayout);
        blankGenericProfileActionJPanelLayout.setHorizontalGroup(
            blankGenericProfileActionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        blankGenericProfileActionJPanelLayout.setVerticalGroup(
            blankGenericProfileActionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout genericProfileActionsJPanelLayout = new javax.swing.GroupLayout(genericProfileActionsJPanel);
        genericProfileActionsJPanel.setLayout(genericProfileActionsJPanelLayout);
        genericProfileActionsJPanelLayout.setHorizontalGroup(
            genericProfileActionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genericProfileActionsJPanelLayout.createSequentialGroup()
                .addComponent(genericProfileActionsJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blankGenericProfileActionJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(genericProfileActionsJPanelLayout.createSequentialGroup()
                .addComponent(newActionJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteActionJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveJButton)
                .addContainerGap())
        );
        genericProfileActionsJPanelLayout.setVerticalGroup(
            genericProfileActionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genericProfileActionsJPanelLayout.createSequentialGroup()
                .addGroup(genericProfileActionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActionJButton)
                    .addComponent(deleteActionJButton)
                    .addComponent(saveJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(genericProfileActionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blankGenericProfileActionJPanel, 0, 296, Short.MAX_VALUE)
                    .addComponent(genericProfileActionsJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(genericProfileActionsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(genericProfileActionsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setModel()
    {
        DefaultListModelHelper defaultListModelHelper = 
            this.getGenericProfileActions().getDefaultListModelHelper();
        
        if(defaultListModelHelper.getListModel().getSize() > 0)
        {
            this.genericProfileActionsJList.setModel(
                defaultListModelHelper.getListModel());
        }
    }
    
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveJButtonActionPerformed
    {//GEN-HEADEREND:event_saveJButtonActionPerformed
// TODO add your handling code here:
        try
        {
            this.getGenericProfileActions().save();
        }
        catch (Exception e)
        {
            logUtil.put(this.commonStrings.EXCEPTION, this, "saveJButtonActionPerformed", e);
        }
    }//GEN-LAST:event_saveJButtonActionPerformed
    
    private void updateProfileActionUI(String profileActionNameString)
    {
        this.blankGenericProfileActionJPanel.removeAll();
        
        if(profileActionNameString != null)
        {
            GenericProfileAction genericProfileAction =
                this.getGenericProfileActions().getAction(
                profileActionNameString);
            
            this.setGenericProfileActionJPanel(
                new GenericProfileActionJPanel());
            
            this.getGenericProfileActionJPanel().setGenericProfileAction(
                genericProfileAction);

            this.getGenericProfileActionJPanel().updateProfileActionUI();

            javax.swing.GroupLayout layout =
                (javax.swing.GroupLayout)
                this.blankGenericProfileActionJPanel.getLayout();
            
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 395, Short.MAX_VALUE)
                .addComponent(
                this.getGenericProfileActionJPanel(),
                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 256, Short.MAX_VALUE)
                .addComponent(
                this.getGenericProfileActionJPanel(),
                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
            
            logUtil.put("Setting Configuration Profile Actions JPanel", this,
                "genericProfileActionsJListValueChanged");
        }
    }
    
    private void genericProfileActionsJListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_genericProfileActionsJListValueChanged
    {//GEN-HEADEREND:event_genericProfileActionsJListValueChanged
// TODO add your handling code here:
        try
        {
            String profileActionNameString =
                (String) this.genericProfileActionsJList.getSelectedValue();
            
            this.updateProfileActionUI(profileActionNameString);
        }
        catch (Exception e)
        {
            logUtil.put(this.commonStrings.EXCEPTION, this, "genericProfileActionsJListValueChanged", e);
        }
    }//GEN-LAST:event_genericProfileActionsJListValueChanged
    
    private void okNewProfileActionJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okNewProfileActionJButtonActionPerformed
    {//GEN-HEADEREND:event_okNewProfileActionJButtonActionPerformed
// TODO add your handling code here:
        try
        {
            String newActionName = this.newProfileActionJTextField.getText();
            this.getGenericProfileActions().add(newActionName);
            
            this.setModel();
            
            this.genericProfileActionsJList.setSelectedValue(newActionName, true);
            
            this.newProfileActionJDialog.setVisible(false);
            
            this.updateProfileActionUI(newActionName);
        }
        catch (Exception e)
        {
            logUtil.put(this.commonStrings.EXCEPTION, this, "okNewProfileActionJButtonActionPerformed", e);
        }
    }//GEN-LAST:event_okNewProfileActionJButtonActionPerformed
    
    private void deleteActionJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteActionJButtonActionPerformed
    {//GEN-HEADEREND:event_deleteActionJButtonActionPerformed
// TODO add your handling code here:
        try
        {
            Object[] object = this.genericProfileActionsJList.getSelectedValues();
            for(int index = 0; index < object.length; index++)
            {
                String nextSelectedValueString = (String) object[index];
                this.getGenericProfileActions().remove(nextSelectedValueString);
            }
            
            this.selectFirstElement();
        }
        catch (Exception e)
        {
            logUtil.put(this.commonStrings.EXCEPTION, this, "deleteActionJButtonActionPerformed", e);
        }
    }//GEN-LAST:event_deleteActionJButtonActionPerformed
    
    public void selectFirstElement() throws Exception
    {
        this.setModel();

        if(this.genericProfileActionsJList.getModel().getSize() > 0)
        {
            this.genericProfileActionsJList.setSelectedValue(
                this.genericProfileActionsJList.getModel().getElementAt(0), true);
            
            this.updateProfileActionUI(
                (String) this.genericProfileActionsJList.getModel().getElementAt(0));
        }
        else
        {
            //Clear the action window
            this.blankGenericProfileActionJPanel.removeAll();
            this.blankGenericProfileActionJPanel.repaint();
        }
    }

    public GenericProfileActionJPanel getGenericProfileActionJPanel()
    {
        return genericProfileActionJPanel;
    }

    public void setGenericProfileActionJPanel(GenericProfileActionJPanel genericProfileActionJPanel)
    {
        this.genericProfileActionJPanel = genericProfileActionJPanel;
    }

    public GenericProfileActions getGenericProfileActions()
    {
        return genericProfileActions;
    }

    public void setGenericProfileActions(GenericProfileActions genericProfileActions)
    {
        this.genericProfileActions = genericProfileActions;
    }
    
    private void newActionJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newActionJButtonActionPerformed
    {//GEN-HEADEREND:event_newActionJButtonActionPerformed
// TODO add your handling code here:
        this.newProfileActionJDialog.setVisible(true);
    }//GEN-LAST:event_newActionJButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blankGenericProfileActionJPanel;
    private javax.swing.JButton deleteActionJButton;
    private javax.swing.JList genericProfileActionsJList;
    private javax.swing.JPanel genericProfileActionsJPanel;
    private javax.swing.JScrollPane genericProfileActionsJScrollPane;
    private javax.swing.JButton newActionJButton;
    private javax.swing.JDialog newProfileActionJDialog;
    private javax.swing.JLabel newProfileActionJLabel;
    private javax.swing.JTextField newProfileActionJTextField;
    private javax.swing.JButton okNewProfileActionJButton;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
    
}
