/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package org.allbinary.graphics.j2me.workarea.properties;

import javax.swing.*;

public class PropertiesJPanel extends javax.swing.JPanel
{   
   //private WorkAreaJPanelInterface workArea;
      
   public PropertiesJPanel()//WorkAreaJPanelInterface workArea)
   {
      //this.workArea = workArea;
      this.initComponents();
   }
   
   public void set(JPanel panel)
   {      
      this.workAreaPropertiesJPanel.add(panel);      
      this.repaint();
   }   
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */   
   private void initComponents()//GEN-BEGIN:initComponents
   {
      this.workAreaPropertiesJPanel = new javax.swing.JPanel();
      this.modifierJPanel = new javax.swing.JPanel();
      this.copyVerticalJButton = new javax.swing.JButton();
      this.copyHorizontalJButton = new javax.swing.JButton();
      this.rotateJPanel = new javax.swing.JPanel();
      this.rotateJButton = new javax.swing.JButton();
      this.angleJTextField = new javax.swing.JTextField();
      this.jPanel7 = new javax.swing.JPanel();
      this.upJButton = new javax.swing.JButton();
      this.downJButton = new javax.swing.JButton();
      this.jPanel8 = new javax.swing.JPanel();
      this.leftJButton = new javax.swing.JButton();
      this.rightJButton = new javax.swing.JButton();

      setLayout(new java.awt.GridLayout(2, 1));

      this.workAreaPropertiesJPanel.setLayout(new java.awt.GridLayout());

      add(this.workAreaPropertiesJPanel);

      this.modifierJPanel.setLayout(new java.awt.GridLayout(6, 0));

      this.copyVerticalJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.copyVerticalJButton.setText("Copy Vertical");
      this.modifierJPanel.add(this.copyVerticalJButton);

      this.copyHorizontalJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.copyHorizontalJButton.setText("Copy Horizontal");
      this.modifierJPanel.add(this.copyHorizontalJButton);

      this.rotateJPanel.setLayout(new java.awt.GridLayout(1, 2));

      this.rotateJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.rotateJButton.setText("Rotate");
      this.rotateJPanel.add(this.rotateJButton);

      this.angleJTextField.setText("Angle");
      this.rotateJPanel.add(this.angleJTextField);

      this.modifierJPanel.add(this.rotateJPanel);

      this.jPanel7.setLayout(new java.awt.GridLayout(1, 2));

      this.upJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.upJButton.setText("Up");
      this.jPanel7.add(this.upJButton);

      this.downJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.downJButton.setText("Down");
      this.jPanel7.add(this.downJButton);

      this.modifierJPanel.add(this.jPanel7);

      this.jPanel8.setLayout(new java.awt.GridLayout(1, 2));

      this.leftJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.leftJButton.setText("Left");
      this.jPanel8.add(this.leftJButton);

      this.rightJButton.setFont(new java.awt.Font("Dialog", 0, 10));
      this.rightJButton.setText("Right");
      this.jPanel8.add(this.rightJButton);

      this.modifierJPanel.add(this.jPanel8);

      add(this.modifierJPanel);

   }//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton rotateJButton;
   private javax.swing.JButton copyVerticalJButton;
   private javax.swing.JButton leftJButton;
   private javax.swing.JPanel rotateJPanel;
   private javax.swing.JTextField angleJTextField;
   private javax.swing.JPanel workAreaPropertiesJPanel;
   private javax.swing.JPanel modifierJPanel;
   private javax.swing.JButton upJButton;
   private javax.swing.JPanel jPanel8;
   private javax.swing.JButton downJButton;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JButton rightJButton;
   private javax.swing.JButton copyHorizontalJButton;
   // End of variables declaration//GEN-END:variables
   
}
