/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package org.allbinary.input.automation.module.generic.configuration.profile.actions.script;

import org.allbinary.input.automation.actions.script.condition.ProfileActionScriptConditionInterface;
import org.allbinary.input.automation.module.generic.configuration.profile.actions.GenericProfileAction;
import org.allbinary.input.automation.module.generic.configuration.profile.actions.GenericProfileActionJPanel;
import org.allbinary.logic.communication.log.LogUtil;

/**
 *
 * @author  USER
 */
public class RemoveActionScriptItemJPanel extends java.awt.Panel
{
    protected final LogUtil logUtil = LogUtil.getInstance();

    
    private GenericProfileActionJPanel genericProfileActionJPanel;
    private ProfileActionScriptConditionInterface profileActionScriptConditionInterface;
    
    /** Creates new form RemoveActionScriptItemJPanel */
    public RemoveActionScriptItemJPanel(
        GenericProfileActionJPanel genericProfileActionJPanel,
        ProfileActionScriptConditionInterface profileActionScriptConditionInterface)
    {
        initComponents();
        
        this.genericProfileActionJPanel = genericProfileActionJPanel;
        this.profileActionScriptConditionInterface = profileActionScriptConditionInterface;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        removeJButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout());

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                removeJButtonActionPerformed(evt);
            }
        });

        add(removeJButton);

    }// </editor-fold>//GEN-END:initComponents

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeJButtonActionPerformed
    {//GEN-HEADEREND:event_removeJButtonActionPerformed
        final GenericProfileAction genericProfileAction = 
            this.genericProfileActionJPanel.getGenericProfileAction();

        if(genericProfileAction == null) {
            logUtil.put("GenericProfileAction was null", this, "removeJButtonActionPerformed");
            return;
        }
        
        genericProfileAction.getGenericProfileActionScript().removeCondition(
            this.profileActionScriptConditionInterface);

        this.genericProfileActionJPanel.updateProfileActionUI();
    }//GEN-LAST:event_removeJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
    
}
