/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.allbinary.game.testgamedemo;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int testgamedemo_icon=0x7f020000;
        public static final int testgamedemo_wait_256_by_256=0x7f020001;
    }
    public static final class id {
        public static final int ad_area_bottom=0x7f060002;
        public static final int ad_area_left=0x7f060003;
        public static final int ad_area_right=0x7f060004;
        public static final int ad_area_top=0x7f060001;
        public static final int testgamedemo=0x7f060000;
        public static final int testgamedemo_gl=0x7f060005;
    }
    public static final class layout {
        public static final int testgamedemo_ad_overlay_layout=0x7f030000;
        public static final int testgamedemo_gl_layout=0x7f030001;
        public static final int testgamedemo_layout=0x7f030002;
    }
    public static final class raw {
    	public static final int error=0x7f040000;
        public static final int licenseinitdata=0x7f040001;
        public static final int partner=0x7f040002;
        public static final int select=0x7f040003;
        public static final int test=0x7f040004;
        public static final int testgamedemo_wait_256_by_256=0x7f040005;
        
        public static final int ouya_a=0x7f040012;
        public static final int ouya_key=0x7f040013;
        public static final int ouya_o=0x7f040014;
        public static final int ouya_u=0x7f040015;
        public static final int ouya_y=0x7f040016;        
        
        public static final int touch_button_128_by_128=0x7f040026;
        public static final int touch_button_64_by_64=0x7f040027;
        public static final int touch_button_create_128_by_128=0x7f040028;
        public static final int touch_button_create_64_by_64=0x7f040029;
        public static final int touch_button_down_arrow_128_by_128=0x7f04002a;
        public static final int touch_button_down_arrow_64_by_64=0x7f04002b;
        public static final int touch_button_generic_action_128_by_128=0x7f04002c;
        public static final int touch_button_generic_action_64_by_64=0x7f04002d;
        public static final int touch_button_join_128_by_128=0x7f04002e;
        public static final int touch_button_join_64_by_64=0x7f04002f;
        public static final int touch_button_leave_128_by_128=0x7f040030;
        public static final int touch_button_leave_64_by_64=0x7f040031;
        public static final int touch_button_login_128_by_128=0x7f040032;
        public static final int touch_button_login_64_by_64=0x7f040033;
        public static final int touch_button_next_128_by_128=0x7f040034;
        public static final int touch_button_next_64_by_64=0x7f040035;
        public static final int touch_button_refresh_128_by_128=0x7f040036;
        public static final int touch_button_refresh_64_by_64=0x7f040037;
        public static final int touch_button_start_128_by_128=0x7f040038;
        public static final int touch_button_start_64_by_64=0x7f040039;
        public static final int touch_button_add_local_player_128_by_128=0x7f040038;
        public static final int touch_button_add_local_player_64_by_64=0x7f040039;
        public static final int touch_button_strafe_left_arrow_128_by_128=0x7f04003a;
        public static final int touch_button_strafe_left_arrow_64_by_64=0x7f04003b;
        public static final int touch_button_strafe_right_arrow_128_by_128=0x7f04003c;
        public static final int touch_button_strafe_right_arrow_64_by_64=0x7f04003d;
        public static final int touch_button_turn_left_arrow_128_by_128=0x7f04003e;
        public static final int touch_button_turn_left_arrow_64_by_64=0x7f04003f;
        public static final int touch_button_turn_right_arrow_128_by_128=0x7f040040;
        public static final int touch_button_turn_right_arrow_64_by_64=0x7f040041;
        public static final int touch_button_up_arrow_128_by_128=0x7f040042;
        public static final int touch_button_up_arrow_64_by_64=0x7f040043;
        
        public static final int touch_button_generic_action_arrow_64_by_64=0x7f040009;

    }
    public static final class string {
        public static final int progressbar_in_title_string=0x7f050001;
        public static final int testgamedemo_app_name=0x7f050000;
    }
}
