/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package allbinary.graphics.j2me.workarea.color;

/**
 *
 * @author  Administrator
 */
public class ColorChooser extends javax.swing.JPanel
{
   
   /** Creates new form ColorChooser */
   public ColorChooser()
   {
      initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      jColorChooser1 = new javax.swing.JColorChooser();

      setLayout(new java.awt.BorderLayout());

      add(jColorChooser1, java.awt.BorderLayout.CENTER);

   }//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JColorChooser jColorChooser1;
   // End of variables declaration//GEN-END:variables
   
}
