/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package allbinary.input.automation.module.generic.configuration.profile.actions.script.condition.processors.input;

/**
 *
 * @author  USER
 */
public class InputAutomationTypeJPanel extends javax.swing.JPanel
{
    
    /** Creates new form InputAutomationTypeJPanel */
    public InputAutomationTypeJPanel()
    {
        initComponents();
    }

    public javax.swing.JComboBox getInputAutomationTypeJComboBox()
    {
        return inputAutomationTypeJComboBox;
    }

    public void setInputAutomationTypeJComboBox(javax.swing.JComboBox inputAutomationTypeJComboBox)
    {
        this.inputAutomationTypeJComboBox = inputAutomationTypeJComboBox;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        inputAutomationTypeJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        inputAutomationTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DirectX", "DirectX 8", "Low Level", "Java Robot" }));

        jLabel1.setText("Input Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAutomationTypeJComboBox, 0, 98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(inputAutomationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox inputAutomationTypeJComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
