/*
* AllBinary Open License Version 1
* Copyright (c) 2011 AllBinary
* 
* By agreeing to this license you and any business entity you represent are
* legally bound to the AllBinary Open License Version 1 legal agreement.
* 
* You may obtain the AllBinary Open License Version 1 legal agreement from
* AllBinary or the root directory of AllBinary's AllBinary Platform repository.
* 
* Created By: Travis Berthelot
* 
*/
package allbinary.input.automation.module.generic.configuration.profile.actions.script;

/**
 *
 * @author  USER
 */
public class ActionScriptItemJPanel extends javax.swing.JPanel
{
    
    /** Creates new form ActionScriptItemJPanel */
    public ActionScriptItemJPanel()
    {
        initComponents();
    }

    public javax.swing.JPanel getNewActionScriptInputJPanel()
    {
        return newActionScriptInputJPanel;
    }

    public void setNewActionScriptInputJPanel(javax.swing.JPanel newActionScriptInputJPanel)
    {
        this.newActionScriptInputJPanel = newActionScriptInputJPanel;
    }

    public javax.swing.JPanel getRemoveJPanel()
    {
        return removeJPanel;
    }

    public void setRemoveJPanel(javax.swing.JPanel removeJPanel)
    {
        this.removeJPanel = removeJPanel;
    }

    public javax.swing.JPanel getScriptItemJPanel()
    {
        return scriptItemJPanel;
    }

    public void setScriptItemJPanel(javax.swing.JPanel scriptItemJPanel)
    {
        this.scriptItemJPanel = scriptItemJPanel;
    }

    public javax.swing.JPanel getNewActionScriptConditionJPanel()
    {
        return newActionScriptConditionJPanel;
    }

    public void setNewActionScriptConditionJPanel(javax.swing.JPanel newActionScriptConditionJPanel)
    {
        this.newActionScriptConditionJPanel = newActionScriptConditionJPanel;
    }

    public javax.swing.JPanel getChildActionScriptConditionJPanel()
    {
        return childActionScriptConditionJPanel;
    }

    public void setChildActionScriptConditionJPanel(javax.swing.JPanel childActionScriptConditionJPanel)
    {
        this.childActionScriptConditionJPanel = childActionScriptConditionJPanel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        newActionScriptInputJPanel = new javax.swing.JPanel();
        childActionScriptConditionJPanel = new javax.swing.JPanel();
        newActionScriptConditionJPanel = new javax.swing.JPanel();
        scriptItemJPanel = new javax.swing.JPanel();
        removeJPanel = new javax.swing.JPanel();

        newActionScriptInputJPanel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout childActionScriptConditionJPanelLayout = new javax.swing.GroupLayout(childActionScriptConditionJPanel);
        childActionScriptConditionJPanel.setLayout(childActionScriptConditionJPanelLayout);
        childActionScriptConditionJPanelLayout.setHorizontalGroup(
            childActionScriptConditionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        childActionScriptConditionJPanelLayout.setVerticalGroup(
            childActionScriptConditionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        newActionScriptConditionJPanel.setLayout(new java.awt.GridLayout(1, 0));

        scriptItemJPanel.setLayout(new java.awt.GridLayout(1, 1));

        removeJPanel.setLayout(new java.awt.GridLayout(1, 1));

        removeJPanel.setMinimumSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scriptItemJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
            .addComponent(newActionScriptInputJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addComponent(newActionScriptConditionJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addComponent(childActionScriptConditionJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scriptItemJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(removeJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childActionScriptConditionJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newActionScriptConditionJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newActionScriptInputJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel childActionScriptConditionJPanel;
    private javax.swing.JPanel newActionScriptConditionJPanel;
    private javax.swing.JPanel newActionScriptInputJPanel;
    private javax.swing.JPanel removeJPanel;
    private javax.swing.JPanel scriptItemJPanel;
    // End of variables declaration//GEN-END:variables
    
}
